type: choice
is_multiple_choice: false
options:
- text: Code inside the <code>finally</code> construct will be executed if no exceptions
    are thrown in <code>try</code>.
  is_correct: false
- text: Code inside the <code>finally</code> construct will always be executed if
    the try-catch block is reached.
  is_correct: true
- text: It is a way for programmers to vent frustration - "Finally! I got rid of all
    the exceptions."
  is_correct: false
- text: If a <code>finally</code> construct is specified, it means we want the program
    to gracefully exit if any exceptions are thrown in <code>try</code>.
  is_correct: false
message_correct: Congratulations!
message_incorrect: Incorrect solution
files:
- name: src/Main.java
  visible: true
  text: |-
    public class Main {
       public static void main(String[] args) {

          // a try-catch-finally block
          int i = 0;
          int diver = 0;

          try {
             i = i/diver;
          } catch (ArithmeticException ae) {
             System.err.println("div by zero");
          } finally {
             i = i + 1;
          }
       }
    }
  learner_created: false
status: Solved
feedback:
  message: Congratulations!
  time: Tue, 16 Mar 2021 03:11:42 UTC
record: -1
selected_options:
- 1
